### PR TITLE
docs: Pip Executable var needs to be set

### LINKED ISSUE #26: docs: Pip Executable var needs to be set
# Actual Behaviour
If using the [example playbook ](https://github.com/geerlingguy/ansible-role-ansible/blob/e9a19b1a79cff2bfba81911467509169bf65ef84/README.md?plain=1#L48C1-L48C1)

The Task fails:
```bash
TASK [geerlingguy.ansible : Install Ansible via Pip.] **************************************************************************
fatal: [examle_host]: FAILED! => {"changed": false, "msg": "Unable to find any of  to use.  pip needs to be installed."}
```
Full run:
```bash
TASK [geerlingguy.pip : Ensure Pip is installed.] ******************************************************************************
ok: [examle_host]

TASK [geerlingguy.pip : Ensure pip_install_packages are installed.] ************************************************************
skipping: [examle_host]

TASK [geerlingguy.ansible : Set the package state based on how Ansible is installed.] ******************************************
ok: [examle_host]

TASK [geerlingguy.ansible : Set up Ansible on RedHat.] *************************************************************************
skipping: [examle_host]

TASK [geerlingguy.ansible : Set up Ansible on Fedora.] *************************************************************************
skipping: [examle_host]

TASK [geerlingguy.ansible : Set up Ansible on Ubuntu.] *************************************************************************
skipping: [examle_host]

TASK [geerlingguy.ansible : Set up Ansible on Debian.] *************************************************************************
skipping: [examle_host]

TASK [geerlingguy.ansible : Set up Ansible using Pip.] *************************************************************************
included: /home/[example_user]/.ansible/roles/geerlingguy.ansible/tasks/setup-pip.yml for [example_host]

TASK [geerlingguy.ansible : Install Ansible via Pip.] **************************************************************************
fatal: [examle_host]: FAILED! => {"changed": false, "msg": "Unable to find any of  to use.  pip needs to be installed."}
```

## Solution
The `ansible_pip_executable: pip3` needs to be set as [in the CI build](https://github.com/geerlingguy/ansible-role-ansible/blob/e9a19b1a79cff2bfba81911467509169bf65ef84/molecule/default/pip.yml#L8)

### PR DESCRIPTION
**Pull request by JakobLichterfeld**
closes #26

### CODE REVIEW

**Comment by MorganLindqvist** [comment]
Hi,
I would propose that we change so the default value is pip and not empty. This will make sure we do not break backwards compability.

**Comment by JakobLichterfeld** [comment]
> Hi, I would propose that we instead change so the default value is pip and not empty. This will make sure we do not break backwards compability.

Hi, 
I do not understand your argument. Setting a default variable will break backwards compatibility.
This modification merely reflects the current status in the documentation and does not require any code changes, thus ensuring complete backwards and forwards compatibility.

**Comment by MorganLindqvist** [comment]
I was unclear.

In the last PR (https://github.com/geerlingguy/ansible-role-ansible/pull/25) the possibility to set the executable was introduced. Before that PR the "default" executable name was pip. That PR changed the default value to be empty. breaking the backwards compatibility.

So when I updated my local version of the role my scripts broke. This will happen for everyone else using the pip as installation tool. This PR will inform people how to solve it. But my proposal would be to change the default behavior so that old ansible scripts using this role starts working again.

Changing default value from none to pip will not break backwards compatibility for scripts using the current version.

Keeping your text in the readme file can off course be kept to should what could be done.

If you prefer I can create a separate PR solving the backwards compatibility problem introduced in the previous PR.

**Comment by geerlingguy** [comment]
It shouldn't need to be set, though:

```yaml
executable: "{{ ansible_pip_executable | default(omit) }}"
```

The `default(omit)` should make it so there is nothing set at all if you have it set to `''`...

**Comment by MorganLindqvist** [comment]
If it is not set, one gets the error message described in the issue #26

**Pull request closed without merging**
